name: Profile
description: About me.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  adaptive_breakpoints: ^0.1.4
  flutter_markdown: ^0.6.10+3
  google_fonts: ^5.1.0
  http: ^1.1.0
  webview_flutter: ^3.0.4
  webview_flutter_web: ^0.1.0+4
  hooks_riverpod: ^2.0.0-dev.9
  flutter_hooks: ^0.18.5+1
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  go_router: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false

  assets:
    enabled: true
    package_parameter_enabled: false
    style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs: []

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/
